config/routes.rb
Rails.application.routes.draw do

  root "sites#home"
    
  resources :members do
    resources :loans
    
    collection do 
      post 'import'
      get  'upload'
    end 
  end
    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
  
    belongs_to :member

    validates :amount, presence: true
    validates :repayment_duration, presence: true
    validates :interest, presence: true
    validates :start_date, presence: true
    validates :contract_number, presence: true
    
    scope :ordered, -> { order(start_date: :asc) }
    
    def total_amount_with_interest(amount, interest)
      i = 1 + (interest/100)
      amount * i
    end    
    
    def loan_interest_amount(amount_with_interest, amount)
      amount_with_interest - amount
    end
    
    def monthly_repayment(duration, loan_amount)
      loan_amount.to_f.ceil / duration 
    end
    
    def final_repayment_amount(amount_with_interest, duration)
      amount_with_interest % duration
    end
    
    def final_repayment_date(start_date, duration)
      start_date + (duration + 1).months
    end
    
    def advance_start_date_by_a_month(start_date)
      start_date + 1.months
    end
    
end

app/models/member.rb
class Member < ApplicationRecord
  
   has_many :loans, dependent: :destroy

   validates :name, presence: true
   validates :ic_number, presence: true, uniqueness: true, numericality: { only_integer: true}
   
   # validates :ic_number,
   #            presence: true, uniqueness: true,
   #            format: { with: /\d{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])/, message: "Format No Kad Pengenalan salah" }
   validates :number, presence: true, uniqueness: true

   scope :ordered, -> { order(name: :asc) }
   
   def self.import_return_count(file)
     
     @counter = 0 
     
     CSV.foreach(file.path) do |row|
       name, ic_number, number = row
       member = Member.create(name: name, ic_number: ic_number, number: number)
       @counter += 1 if member.persisted?
     end
     
     # If you want to remove headers then uncomment the code below and comment the above code
     # CSV.foreach(file.path, headers: true) do |row|
     #   member = Member.create(name: row["name"], ic_number: row["ic_number"], number: row["number"])
     #   @counter += 1 if member.persisted?
     # end
     
     return @counter
     
   end
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  
  before_action   :set_member
  before_action   :set_loan, only: %i[ show edit update destroy]
  
  
  def new
    @loan = @member.loans.build
  end

  def create
    @loan = @member.loans.build(loan_params)
    temporary_add_values # Temporary update attributes so that validation (below) can pass

    if @loan.save
      
      # Calculating the loan
      loan_calculation
      
      #Updating the loan calculation
      @loan.update!(amount_with_interest: @awi, interest_amount: @ia, repayment_amount: @ra, final_payment_amount: @fpa, 
                    end_date: @ed)
                    
      respond_to do |format| 
        format.html { redirect_to member_path(@member), notice: "Pinjaman telah diwujudkan" }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
  end
  
  def update  
    
      if @loan.update(loan_params)
        
        # Calculating the loan 
        loan_calculation
        
        #Updating the loan calculation
        @loan.update!(amount_with_interest: @awi, interest_amount: @ia, repayment_amount: @ra, final_payment_amount: @fpa, 
                      end_date: @ed)
        
        respond_to do |format|
          format.html { redirect_to member_url(@member), notice: "Pinjaman telah di ubah" }
        end 
      else
        format.html { render :edit, status: :unprocessable_entity }
      end 
  end

  def show
    @repayment_date = @loan.start_date + 1.months
    @loan_amount    = @loan.amount_with_interest - @loan.repayment_amount
    @period         = @loan.repayment_duration
    @payment        = @loan.repayment_amount
    
  end
  
  def destroy
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to member_url(@member), notice: "Loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  private
  
  def set_member
    @member = Member.find(params[:member_id])
  end
  
  def set_loan
    @loan = @member.loans.find(params[:id])
  end
  
  def loan_params
    params.require(:loan).permit(:start_date, :amount, :repayment_duration,
                             :contract_number, :interest)
  end
  
  # Temporary set values for attributes to allow for validation to check the forms
  def temporary_add_values
    @loan.amount_with_interest = 0
    @loan.interest_amount = 0
    @loan.repayment_amount = 0
    @loan.final_payment_amount = 0
    @loan.end_date = Time.now.to_date
  end
  
  def loan_calculation
    
    #Loan calculation methods
    @awi = @loan.total_amount_with_interest(@loan.amount, @loan.interest)
    @ia  = @loan.loan_interest_amount(@awi, @loan.amount)
    @ra  = @loan.monthly_repayment(@loan.repayment_duration, @awi)
    @fpa = @loan.final_repayment_amount(@awi, @loan.repayment_duration)
    @ed  = @loan.final_repayment_date(@loan.start_date, @loan.repayment_duration)
    
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all.ordered
  end

  # GET /members/1 or /members/1.json
  def show
    @loans = @member.loans.ordered
    # @loan  = @member.loans.new
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
    @member = Member.find_by(id: params[:id])
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)
  
    if @member.save
      
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update

      if @member.update(member_params)
        redirect_to members_path, notice: "Member was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 

      end

  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    
    redirect_to members_path, alert: "Member was successfully destroyed." 
   
    # respond_to do |format|
    #   format.html { redirect_to members_path, notice: "Member was successfully destroyed." }
    # end
  end
  
  def upload
  end
  
  def import
    if params[:file].nil?
      redirect_to members_path
    else
      counter = Member.import_return_count(params[:file])
      flash.now[:notice] =  "#{counter} members added"
      @members = Member.all.ordered

      # respond_to do |format|
      #   format.turbo_stream { flash.now[:notice] = "#{@counter} members added"}
      # end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:name, :ic_number, :number)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def form_error_notification(object)
        if object.errors.any?
          tag.div class: "error-message" do
            object.errors.full_messages.to_sentence.capitalize
          end
        end
    end
end

app/helpers/loans_helper.rb
module LoansHelper
  
  def next_repayment(date, amount, payment)
    @repayment_date = date + 1.months
    @loan_amount    = amount - payment
  end 
  
  def final_zero_amount(final_payment, payment, loan_amount)
    loan_amount + payment - final_payment
  end
  
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/_error.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_flash.html.erb
  <% if notice.present? %>
    <p class="opacity-75 py-2 px-3 bg-green-600 mb-5 text-slate-100 font-medium rounded-full inline-block" id="notice" >
      <%= notice %>
    </p>
  <% end %>


  <% if alert.present? %>
    <p class="opacity-75 py-2 px-3 bg-red-700 mb-5 text-slate-300 font-medium rounded-full inline-block" id="notice" >
      <%= alert %>
    </p>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-50 font-sans">
  <head>
    <title>Muz's Profile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col justify-between h-full">
	  
    <main class="container text-sm mx-auto mt-10 px-5">

      <div id="flash" class="flash flex justify-center">
          <%= render "layouts/flash" %>
      </div>
	  
      <%= yield %>

    </main>
	
	<footer class="bg-gray-900 text-slate-300 lg:text-left">
		<div class="flex flex-row justify-between ">
			<div class="m-auto">
			    <%= link_to root_path, class: "hover:text-blue-400" do %>
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
					  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
					</svg>	
				<% end %>
			</div>
	
	 		<div class="m-auto text-sm text-center p-4">
				<p>Made with ❤️ by Muz | Get in touch <%= mail_to "mus.ariff@gmail.com", "@", class: "transform hover:text-blue-400 hover:scale-110" %>
				</p>								
		    </div>
	  </div>
	</footer>
	
  </body>
</html>

app/views/loans/_form.html.erb
<div class="relative h-78 w-full px-4 py-4 border border-2 border-grey-500 border-dotted mt-5">
<%= form_with(model: [member, loan], class: "content flex mt-8") do |form| %>

	<div class="w-full grid grid-cols-3 gap-4 justify-items-stretch">

		<div class="col-span-3">
			<%= form_error_notification(loan) %>
		</div>	
	
		<div class="w-32 justify-self-center">

		      <%= form.label "Amount", class: "block text-sm font-medium text-gray-600 text-left" %>

			  <div class="flex">
				  <span class="inline-flex items-center px-3 text-sm text-slate-100 bg-gray-800 rounded-l-md border border-r-0 border-gray-300">
				      RM
				    </span>
			      <%= form.text_field :amount, class: "rounded-none rounded-r-md border focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5" %>
			  </div>
		</div>

	    <div class="w-32 justify-self-center">

		      <%= form.label "Duration", class: "block text-sm font-medium text-gray-600 text-left" %>

			  <div class="flex">
				  	<%= form.text_field :repayment_duration, class: "rounded-none rounded-l-md focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5" %>
					<span class="inline-flex items-center px-3 text-sm text-slate-100 bg-gray-800 rounded-r-md border border-r-0 border-gray-30">
					      Months
					</span>
			  </div>

	    </div>

		<div class="w-24 justify-self-center">
		      <%= form.label "Interest", class: "block text-sm font-medium text-gray-600 text-left" %>

			  <div class="flex">
			      <%= form.text_field :interest, class: "rounded-none rounded-l-md focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5" %>
				  <span class="inline-flex items-center px-3 text-sm text-slate-100 bg-gray-800 rounded-r-md border border-r-0 border border-gray-30">
				      %
				    </span>
			  </div>
		</div>

	  	<div class="justify-self-center w-36">
  	      <%= form.label "Contract number", class: "block text-sm font-medium text-gray-600 text-left" %>

  		  <div class="flex">
  		      <%= form.text_field :contract_number, class: "rounded-md border focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5" %>
  		  </div>
	  	</div>
		
		<div class="justify-self-center w-full">
		      <%= form.label "Loan starts on", class: "block text-sm font-medium text-gray-600 text-center" %>

			  <div class="flex justify-center">
			      <%= form.date_select :start_date, order: [:day, :month, :year], class: "rounded-none rounded-l-md focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5" %>
			  </div>
		</div>
		
	    <div class="flex items-end flex-row-reverse justify-center">
	    	<div class="flex-initial ml-3">
		  		<%= form.submit class: "button-primary" %>
		  	</div>

		  	<div class="flex-initial">
		  		<%= link_to sanitize("&larr;"), member_path(@member), 
	  			class: "flex flex-col items-center rounded-md border border-slate-600 py-2 px-2 text-black font-medium cursor-pointer" %>
	
		  	</div>
		</div>

<% end %>
</div>

app/views/loans/_loan.html.erb
<%= turbo_frame_tag loan do %>

<div class="relative h-78 w-full px-4 py-4 border border-2 border-grey-500 border-dotted mt-5 mb-8">
  
	<!-- Elements around each corner of the content box -->
	<div class="absolute top-2 left-2">
		<div class="flex items-center">
			<p class="text-sm">Contract: <%= loan.contract_number %></p>
		</div>
	</div>
	
	<div class="absolute top-2 right-2">
		<div class="flex items-center">
			<p class="text-sm"><%= loan.start_date.strftime("%-d %b %Y") %></p>
		</div>
	</div>
	
	<div class="absolute bottom-2 right-2">
		<div class="flex items-center">
            
			<%= link_to edit_member_loan_path(@member, loan), class: "w-4 mr-2 transform hover:text-red-400 hover:scale-110" do %>
				 <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				   <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
				 </svg>
            <% end %>
			
		    <%= link_to sanitize("&rarr;"), member_loan_path(@member, loan), 
				data: { turbo_frame: "_top"}, 
		        class: "hover:text-blue-400" %>
			
		</div>
	</div>
	
	<div class="absolute bottom-2 left-2">
		<div class="flex items-center">
            
			<%= button_to member_loan_path(@member, loan), method: :delete, data: { turbo_frame: "_top"}, class: "w-4 mr-2 transform hover:text-red-400 hover:scale-110" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            <% end %>
			
		</div>
	</div>

	<!-- Information in the middle of the box -->	
	<div class="grid grid-cols-1">
		<div class="col-span-1 items-center mt-5">
			<p class="text-sm text-center">Loan amount: <%= number_to_currency(loan.amount, :unit => "RM ") %></p>
		</div>
		
		<div class="col-span-1 items-center mt-3">
			<p class="text-sm text-center">Duration: <%= loan.repayment_duration %> months</p>
		</div>
		
		<div class="col-span-1 items-center mt-3">
			<p class="text-sm text-center">Monthly repayment: <%= number_to_currency(loan.repayment_amount, :unit => "RM ") %></p>
		</div>		
		
		<div class="col-span-1 items-center mt-3">
			<p class="text-sm text-center">Final payment: <%= number_to_currency(loan.final_payment_amount, :unit => "RM ") %></p>
		</div>
		
		<div class="col-span-1 items-center mt-3">
			<p class="text-sm text-center">Last payment date: <%= loan.end_date.strftime("%-d %b %Y") %></p>
		</div>
	
	</div>
	
</div>

<% end %>

app/views/loans/create.turbo_stream.erb
<%= turbo_stream.prepend "loans", @loan %>

<%= turbo_stream.update Loan.new, "" %>

app/views/loans/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= link_to sanitize("&larr; Kembali ke ahli"), member_path(@member), 
      class: "hover:text-blue-400" %>

  <div class="mt-10">
    <h1 class="font-bold text-4xl">Editing loan</h1>
  </div>

  <%= turbo_frame_tag @loan do %>
  	  <%= render "form", member: @member, loan: @loan %>
  <% end %>

</div>

app/views/loans/new.html.erb
<div class="mx-auto w-full">

  <%= link_to sanitize("&larr; Kembali ke ahli"), member_path(@member), 
      class: "hover:text-blue-400" %>

  <div class="mt-10">
    <h1 class="font-bold text-3xl text-blue-400 text-left underline underline-offset-8">Pinjaman baru</h1>
  </div>
  
  <%= turbo_frame_tag @loan do %>
	  <%= render "form", member: @member, loan: @loan %>
  <% end %>

</div>

app/views/members/_member.html.erb
  <tr class="border-b border-gray-200 hover:bg-gray-100">
	  
    <td class="py-3 px-6 text-left">
      <div class="flex items-center">
        <%= member.name %>
      </div>
    </td>

    <td class="py-3 px-8 text-left">
      <div class="text-center">
        <%= member.ic_number %>
      </div>
    </td>

    <td class="py-3 px-8">
      <div class="text-center">
        <%= member.number %>
      </div>
    </td>

    <td class="py-3 px-8">
      <div class="text-center">
        <%= member.loans.size %>
      </div>
    </td>

    <td class="py-3 px-6 text-left">
      <div class="flex items-center justify-center">

          <%= link_to member, class: "w-4 mr-2 transform hover:text-blue-400 hover:scale-110" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
          <% end %>

          <%= link_to edit_member_path(member), class: "w-4 mr-2 transform hover:text-green-400 hover:scale-110" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </svg>
          <% end %>
		  
          <%= button_to member_path(member), method: :delete, class: "w-4 mr-2 transform hover:text-red-400 hover:scale-110" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
          <% end %>


      </div>
    </td>
  </tr>

app/views/members/create.turbo_stream.erb
<%= turbo_stream.prepend "member-list" do %>
  <tr class="border-b border-gray-200 hover:bg-gray-100">
	  
    <td class="py-3 px-6 text-left">
      <div class="flex items-center">
        <%= @member.name %>
      </div>
    </td>

    <td class="py-3 px-8 text-left">
      <div class="text-center">
        <%= @member.ic_number %>
      </div>
    </td>

    <td class="py-3 px-8">
      <div class="text-center">
        <%= @member.number %>
      </div>
    </td>

    <td class="py-3 px-8">
      <div class="text-center">
        <%= @member.loans.size %>
      </div>
    </td>

    <td class="py-3 px-6 text-left">
      <div class="flex items-center justify-center">

          <%= link_to @member, class: "w-4 mr-2 transform hover:text-blue-400 hover:scale-110" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
          <% end %>

          <%= link_to edit_member_path(@member), class: "w-4 mr-2 transform hover:text-green-400 hover:scale-110" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
              </svg>
          <% end %>
		  
          <%= button_to member_path(@member), method: :delete, class: "w-4 mr-2 transform hover:text-red-400 hover:scale-110" do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
          <% end %>


      </div>
    </td>
  </tr>
<% end %>

app/views/members/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= link_to sanitize("&larr; Return to all members"), members_path, 
      class: "hover:text-blue-400" %>

  <div class="mt-10">
    <h1 class="font-bold text-4xl">Editing member</h1>
  </div>
  
  	  <%= render "form", member: @member %>

</div>

app/views/members/import.turbo_stream.erb
<%= turbo_stream.update "member-list" do %>
	<%= render @members %>
<% end %>

<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/members/index.html.erb
<div class="flex flex-row items-center">
	<div class="w-1/4">
      <h1 class="font-bold text-4xl px-4">Borrowers</h1>
	</div>
	<div class="w-3/4 ml-10">
	  <%= turbo_frame_tag "new_member" do %>
		    <%= link_to 'New borrower', new_member_path, 
		                class: "button-primary" %>
	  <% end %>
	</div>
</div>

<div class="w-full bg-white shadow-md rounded my-6">

	<table class="min-w-max w-full table-auto">
	  <thead>
	    <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
	        <th class="py-3 px-6 text-left">Name</th>
	        <th class="py-3 px-6 text-center">IC Number</th>
	        <th class="py-3 px-6 text-center">Membership number</th>
	        <th class="py-3 px-6 text-center">Loans</th>
	        <th class="py-3 px-6 text-center">Action</th>
	    </tr>
	  </thead>
	  <tbody id="member-list"class="text-gray-600 text-sm font-light">
  		<%= render @members %>
	  </tbody>

	</table>

</div>

<div class="flex flex-row justify-end">
	<%= turbo_frame_tag "upload_member" do %>
		<%= link_to sanitize("Add members via CSV upload &rarr;"), upload_members_path, 
			class: "py-2 px-2 text-black hover:text-blue-500 font-medium cursor-pointer" %>
	<% end %>
</div>
	

app/views/members/new.html.erb
<%= turbo_frame_tag "new_member" do %>
    <%= render "form", member: @member %>
<% end %>

app/views/members/show.html.erb
<div class="mx-auto w-full">

  <%= link_to sanitize("&larr; Return to members"), members_path, 
      class: "hover:text-blue-400" %>

  <div class="mt-10">
    <div class="grid grid-cols-8 gap-4 rounded-md bg-slate-200 border border-2 border-grey-500 border-dotted px-5 py-5">

      <div class="col-start-1 col-span-2 flex flex-col items-center 
        rounded-full py-3 px-3 bg-zinc-700 font-bold text-slate-200 font-medium">
          <%= @member.number %>
      </div>

      <div class="col-start-4 col-span-4 flex flex-col items-center">
          <h1 class="font-extrabold text-5xl"><%= @member.name %></h1>
      </div>

      <div class="col-start-1 col-span-2 flex flex-col items-center rounded-md px-3">
        <%= @member.ic_number %>
      </div>

    </div>
  </div>
  
  <div class="grid grid-cols-1 divide-y">
	  
	<%= turbo_frame_tag Loan.new do %>
	  <div class="button-center mt-5">
	      <%= link_to 'New Loan', new_member_loan_path(@member), 
	                  class: "button-primary",
	                  data: { turbo_frame: dom_id(Loan.new) } %>
	  </div>
    <% end %>
  </div>
  
	<%= turbo_frame_tag "loans" do %>
	  <%= render @loans, loan: @loans %>
	<% end %>

</div>

app/views/members/upload.html.erb
<%= turbo_frame_tag "upload_member" do %>

	<div class="flex items-center">
	  <div class="mr-3 text-orange-600 hover:text-blue-500">	
		<%= link_to "Download Sample CSV", "/sample_member_list.csv" %>
	  </div>
	  
	  <div class="mr-3">
		  <p> | </p>
  	  </div>
	  <div class="">
		<%= form_tag import_members_path, multipart: true do %>
			<%= file_field_tag :file %>
			<%= submit_tag "Upload members", class: "button-primary" %>
		<% end %>
	  </div>
   </div>

<% end %>